image: $CI_IMAGE

.ace: &ace
    tags: ['ace-x86_64']

.common_only: &common_only
    only:
        - main
        - merge_requests

.build:
    <<: *ace
    <<: *common_only
    stage: build
    variables:
        APP: app
        ELF_PREFIX: kenning-zephyr-runtime
        BOARDS: >
            b_u585i_iot02a
            nrf52840dk/nrf52840
            nrf52840dongle
            stm32f746g_disco
            hifive_unleashed
    before_script:
        - scripts/prepare_zephyr_env.sh
        - scripts/prepare_modules.sh
        - mkdir -p artifacts
    script:
        - |
          source .venv/bin/activate
          if [ "$RUNTIME" != "stub" ]
          then
              RUNTIME_CONF="${RUNTIME}.conf"
          fi
          for BOARD in ${BOARDS}
          do
              BOARD_NAME="${BOARD//\//_}"
              python -m west build -p always -b ${BOARD} ${APP} -- -DEXTRA_CONF_FILE=${RUNTIME_CONF} ${EXTRA_ARGS}
              cp build/zephyr/zephyr.elf artifacts/${ELF_PREFIX}-${RUNTIME}-${BOARD_NAME}.elf
          done
    artifacts:
        paths:
            - artifacts/*.elf
        when: always

.build-demo:
    extends: .build
    variables:
        APP: demo_app
        ELF_PREFIX: kenning-zephyr-runtime-demo

variables:
    GIT_STRATEGY: clone

stages:
    - lint
    - build
    - tests

pre-commit:
    <<: *ace
    <<: *common_only
    stage: lint
    script:
        - pre-commit run --all-files

build-stub:
    extends: .build
    variables:
        RUNTIME: stub

build-tvm:
    extends: .build
    variables:
        RUNTIME: tvm

build-tflite:
    extends: .build
    variables:
        RUNTIME: tflite

build-iree-vmvx:
    extends: .build
    variables:
        RUNTIME: iree_vmvx

build-iree-embedded-elf:
    extends: .build
    variables:
        RUNTIME: iree_embedded_elf

build-demo-tvm:
    extends: .build-demo
    variables:
        RUNTIME: tvm

build-demo-tflite:
    extends: .build-demo
    variables:
        RUNTIME: tflite

build-demo-iree-vmvx:
    extends: .build-demo
    variables:
        RUNTIME: iree_vmvx
        BOARDS: >
            b_u585i_iot02a
            hifive_unleashed

build-demo-iree-embedded-elf:
    extends: .build-demo
    variables:
        RUNTIME: iree_embedded_elf
        BOARDS: >
            b_u585i_iot02a

build-demo-tvm-gen-model:
    extends: .build-demo
    variables:
        RUNTIME: tvm
        ELF_PREFIX: kenning-zephyr-runtime-demo-gen-model
        EXTRA_ARGS: -DCONFIG_KENNING_MODEL_PATH="https://dl.antmicro.com/kenning/models/classification/magic_wand.h5"
        BOARDS: >
            stm32f746g_disco

build-repl:
    extends: .build
    script:
        - |
          source .venv/bin/activate
          for BOARD in ${BOARDS}
          do
              BOARD_NAME="${BOARD//\//_}"
              python -m west build -p always -b ${BOARD} demo_app || true
              python -m west build -t board-repl
              cp build/*.repl artifacts/${BOARD_NAME}.repl
          done
    artifacts:
        paths:
            - artifacts/*.repl
        when: always

test-demo:
    <<: *ace
    <<: *common_only
    stage: tests
    script:
        - python -m pytest -ra -vv --color=yes --report-log=log.json ./tests/demo/test_demo.py
    dependencies:
        - build-demo-tvm
        - build-demo-tflite
        - build-demo-iree-vmvx
        - build-demo-iree-embedded-elf
        - build-demo-tvm-gen-model
        - build-repl
    artifacts:
        paths:
            - log.json
        when: always

unit-tests:
    <<: *ace
    <<: *common_only
    stage: tests
    before_script:
        - scripts/prepare_zephyr_env.sh
    script:
        - source .venv/bin/activate
        - python -m west twister -T tests -p unit_testing
    artifacts:
        paths:
            - twister-out/unit_testing/lib/kenning_inference_lib/**/*.log
        when: always

tuttest:
    <<: *ace
    <<: *common_only
    image: debian:bullseye
    stage: tests
    script:
        - DEBIAN_FRONTEND=noninteractive apt update -qqy && apt-get install -y sudo python3 python3-pip git colorized-logs
        - python3 -m pip install setuptools pip
        - python3 -m pip install git+https://github.com/antmicro/tuttest.git
        - ./scripts/test_readme.sh
