# Copyright (c) 2023-2024 Antmicro <www.antmicro.com>
#
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: apache
      url-base: https://github.com/apache

    - name: dmlc
      url-base: https://github.com/dmlc

    - name: openxla
      url-base: https://github.com/openxla

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import:
        name-allowlist:
          - cmsis
          - cmsis-nn
          - cmsis-dsp
          - hal_nordic
          - hal_stm32
          - segger

    - name: tflite-micro
      remote: zephyrproject-rtos
      revision: main

    - name: tvm
      remote: apache
      revision: main

    - name: dlpack
      remote: dmlc
      revision: main

    - name: iree
      remote: openxla
      revision: 2f40854c548cbe082190d1dd1691a342ffd9006b
      submodules:
        - path: third_party/flatcc
