name: Kenning Zephyr runtime tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    readme-tests:
        runs-on: ubuntu-latest
        container:
            image: debian:bookworm
        steps:
            - name: Checkout sources
              uses: actions/checkout@v4
            - name: Install tuttest dependencies
              run: |
                  apt-get update -qqy
                  apt-get install -qqy --no-install-recommends python3 python3-pip git colorized-logs sudo
                  sudo pip3 install --break-system-packages git+https://github.com/antmicro/tuttest.git
            - name: Run README.md snippets
              run: |
                  ./scripts/test_readme.sh
